name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Show python version
        run: python --version
      - name: Install PlatformIO
        run: python -m pip install platformio==4.3.4
      - name: Build firmware
        run: platformio run
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Show node.js version
        run: node --version
      - name: Install web-ui dependencies
        run: cd web-ui && npm install
      - name: Build web-ui
        run: cd web-ui && npm run build
      - name: Build web-ui filesystem firmware image
        run: cd web-ui && ./build.sh
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/d1_mini/*.bin
